--
#  APISERVER_IMG="quay.io/kubernetes-service-catalog/apiserver:canary"
#  CONTROLLER_MANAGER_IMG="quay.io/kubernetes-service-catalog/controller-manager:canary"

#    docker pull $APISERVER_IMG
#    docker pull $CONTROLLER_MANAGER_IMG
#    docker tag $APISERVER_IMG apiserver:canary
#    docker tag $CONTROLLER_MANAGER_IMG controller-manager:canary
    # Deploy service-catalog
#    oc new-project service-catalog
#    oc process -f /shared/service-catalog.templ.yaml | oc create -f -

# TODO: This is bad. HACK: Wait until apiserver is up
# Tap into cluster events somehow?
#until oc get pods | grep -qiEm1 "apiserver.*?running"; do : ; done
# Get apiserver ip address
#API_SRV_IP=$(/shared/get_apiserver_ip.sh)
#SERVICE_CAT_ENDPOINT="$API_SRV_IP:8081"
#echo "Service Catalog Endpoint: $SERVICE_CAT_ENDPOINT"
#mkdir /home/vagrant/.kube
#cat /shared/kubeconfig.templ.yaml | sed "s|{{SERVICE_CATALOG_ENDPOINT}}|$SERVICE_CAT_ENDPOINT|" \
#  > /home/vagrant/.kube/service-catalog.config
#chown -R vagrant:vagrant /home/vagrant/.kube
