---
  - name: upgrade vim-minimal to avoid conflicts issue
    package:
      name: vim-minimal
      state: latest
    become: true

  - name: install packages
    package:
      name: "{{ item }}"
      state: installed
    with_items:
      - "deltarpm"
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "bridge-utils"
      - "gcc"
      - "docker"
      - "vim"
      - "vim-enhanced"
      - "golang"
      - "glide"
      - "nodejs"
      - "ansible"
    become: True

  - name: Install pip
    easy_install:
      name: pip
      state: latest
    become: True
