---
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: Add Ansible Service Broker Copr Repository
    get_url:
      url: https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker/repo/epel-7/group_ansible-service-broker-ansible-service-broker-epel-7.repo
      dest: /etc/yum.repos.d/ansible-service-broker.repo
      mode: 0644

  - name: install packages
    yum:
      name: "{{ item }}"
      state: installed
    with_items:
      - "deltarpm"
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "bridge-utils"
      - "gcc"
      - "docker"
      - "vim"
      - "vim-enhanced"
      - "golang"
      - "nodejs"
      - "ansible"
      - "python2-docker"
      - "apb"

