---
  - name: Template secret file to be created
    template:
      src: demo-secret.j2
      dest: /tmp/demo-secret.yml
      owner: root
      group: root
      mode: 0644
    register: demo_secret_result

  - name: Login as {{ cluster_user }}
    shell: "{{ oc_cmd }} login -u {{ cluster_user }} -p {{ cluster_user_password }}"

  - name: check if project exists
    shell: "{{ oc_cmd }} get project --no-headers=true | awk '{ print $1 }' | grep -E '^{{ demo_project_name }}( |$)' | cat"
    register: project

  - name: Create a new project for the demo '{{ demo_project_name }}'
    shell: "{{ oc_cmd }} new-project {{ demo_project_name }}"
    register: new_demo_project
    when: project.stdout.find( demo_project_name ) == -1

  - set_fact:
      secret_name: "{{ demo_project_name }}-secret"

  - name: check if secret exists
    shell: "{{ oc_cmd }} get secret --no-headers=true -n {{ demo_project_name }} | awk '{ print $1 }' | grep -E '^{{ secret_name }}( |$)' | cat"
    register: secret

  - name: Creating secret in project
    shell: "{{ oc_cmd }} create -f /tmp/demo-secret.yml"
    when: secret.stdout.find( secret_name ) == -1
