---
  - name: Template secret file to be created
    template:
      src: demo-secret.j2
      dest: /tmp/demo-secret.yml
      owner: root
      group: root
      mode: 0644
    register: demo_secret_result

  - name: Login as {{ cluster_user }}
    shell: "{{ oc_cmd }} login -u {{ cluster_user }} -p {{ cluster_user_password }}"

  - name: Create a new project for the demo '{{ demo_project_name }}'
    shell: "{{ oc_cmd }} new-project {{ demo_project_name }}"
    register: new_demo_project
    ignore_errors: yes

  - name: Creating secret in project
    shell: "{{ oc_cmd }} create -f /tmp/demo-secret.yml"
    when: new_demo_project|succeeded
