#
# We are looking up the ec2 facts and storing them in a host variable
# so a later play can retrieve the data.
#
- hosts: localhost
  gather_facts: True
  tasks:
    - name: EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ instance_name }}"
        region: "{{ aws_region }}"
      register: my_ec2_facts

    - name: Setting fact of my_vpc_id on localhost
      set_fact:
        my_vpc_id: "{{ hostvars.localhost.my_ec2_facts.instances[0].vpc_id }}"

    - name: Get EC2 VPC Subnet A Info
      ec2_vpc_subnet_facts:
        filters:
          vpc-id: "{{ my_vpc_id }}"
          "tag:Name": "{{ vpc_subnet_a_name }}"
        region: "{{ aws_region }}"
      register: my_subnet_info

    - name: Setting fact of my_subnet_id for localhost
      set_fact:
        my_subnet_id: "{{ hostvars.localhost.my_subnet_info.subnets[0].id }}"

- hosts: tag_Name_{{ instance_lookup_value }}
  gather_facts: True
  become: True
  roles:
    - ebs_volumes
    - aws_repo_setup
    - packages
    - docker_setup
    - openshift_setup
    - service_catalog_setup
    - ansible_service_broker_setup
    - demo_prep
