#
# We are looking up the ec2 facts and storing them in a host variable
# so a later play can retrieve the data.
#
- hosts: localhost
  gather_facts: True
  tasks:
    - name: EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ instance_name }}"
        region: "{{ aws_region }}"
      register: my_ec2_facts

- hosts: tag_Name_{{ instance_lookup_value }}
  gather_facts: True
  become: True
  roles:
    - ebs_volumes
    - aws_repo_setup
    - packages
    - docker_setup
    - openshift_setup
    - service_catalog_setup
    - ansible_service_broker_setup
    #- demo_prep
