---
  - name: install packages for AWS Multi-Node Infrastructure
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct

  - name: Install NetworkManager
    yum:
      name: "NetworkManager"
      state: present
    when: deploy_origin

  - name: Enable and Start NetworkManager Service
    systemd:
      name: NetworkManager
      enabled: yes
      state: started
    when: deploy_origin

  - name: Yum Update
    yum:
      name: '*'
      state: latest
    when: not enable_ops_mirror_repo
